### PR TITLE
Update pywikibot to fix editing

### PR DESCRIPTION
**Pull request by simon04**
Addresses issue from https://github.com/konstin/github-wikidata-bot/pull/156#issuecomment-1264622312

### CODE REVIEW

**Comment by konstin** [comment]
Thank you!

**Comment by konstin** [comment]
that indeed fixes it! i've started a complete run now, i'll report when it's done

**Comment by simon04** [comment]
Hi, (not sure where to report/discuss operation problems). The bot stopped working on 2022-10-05 according to https://www.wikidata.org/wiki/Special:Contributions/Github-wiki-bot. Let me know if I can help out.

**Comment by konstin** [comment]
it's still https://github.com/konstin/github-wikidata-bot/pull/156#issuecomment-1264622312 unfortunately; i haven't reactivated the cron job since it still crashes on every run

**Comment by konstin** [comment]
sorry i didn't realize the last test run did actually pass, i reactivated the cron job now

**Pull request merged**
