### PR TITLE
Add qualifier P548 ('version type')

### PR DESCRIPTION
**Pull request by Nudin**
This addresses first half of #15

### CODE REVIEW

**Comment by konstin** [comment]
I don't know what exactly I did when resolving that conflict (The github UI doesn't really tell), but it _looks_ fine to me now.

**Comment by konstin** [comment]
Perfect, I'll merge this then.

**Comment by konstin** [comment]
I've just noticed after [this conversation](https://www.wikidata.org/wiki/User_talk:Konstin#Please_disable_the_github_bot#Please_disable_the_github_bot) that "stable version" in wikidata actually means "supported version" and not "not-prerelease". I'm therefore reverting that change.

**Comment by Nudin** [comment]
> I've just noticed after this conversation that "stable version" in wikidata actually means "supported version" and not "not-prerelease". I'm therefore reverting that change.

Interesting. I have ~1000 software items on my watchlist and most of them use "stable version" also for old stable versions. But it's right to revert this for now, it should be discussed before possible adding it back in – and we should definitely also only add it if there is no P548 set yet. That's my fault.

**Comment by konstin** [comment]
I've wrote [a query](https://query.wikidata.org/#Select%20%3Fitem%20%3FitemLabel%20%3Fsubitem%20%3FsubitemLabel%20where%20%7B%0A%20%20%3Fitem%20wdt%3AP1687%20wd%3AP548.%0A%20%20%3Fsubitem%20wdt%3AP31%2Fwdt%3AP279%2a%20%3Fitem.%0A%20%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20.%20%7D%0A%7D) for checking what values are possible for P548. It seems that this was indeed meant for differentiating between the different stages of prereleases and releases, although obsolete version (Q21683863) and stable version (Q2804309) are suddenly talking about support ranges in their description. This imho a bug in the current wikidata classification. Support for a version would be imho much better expressed by adding an end of life qualifier.

**Comment by Nudin** [comment]
Yes, especially if you look at the [numbers how often the values are used](https://query.wikidata.org/#%23%20values%20used%20with%20P548%20%28version%20type%29%20qualifiers%20of%20P348%20%28software%20version%29%20claims%0ASELECT%20%3Fvalue%20%3FvalueLabel%20%28COUNT%28%3Fvalue%29%20AS%20%3Fcnt%29%20WHERE%20%7B%0A%20%20%3Fitem%20%3Fprop%20%5B%20pq%3AP548%20%3Fvalue%20%5D%20.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%27en%27%20%7D%0A%7D%20GROUP%20BY%20%3Fvalue%20%3FvalueLabel%20ORDER%20BY%20DESC%28%3Fcnt%29) "obsolete version" is used quite rarely.

**Pull request merged**
