### PR TITLE
Add a query to list free software w/o repository

### PR DESCRIPTION
**Pull request by simon04**

### CODE REVIEW

**Comment by Nudin** [comment]
You might not only search for "Free Software" but also for Open Source, etc. Something like:
```
  {
   ?floss p:P31 ?val.
   ?val v:P31/wdt:P279* wd:Q506883.
  } Union {
   ?floss p:P31 ?val.
   ?val v:P31/wdt:P279* wd:Q341.
  } Union {
   ?floss p:P31 ?val.
   ?val v:P31/wdt:P279* wd:Q1130645.
  }
```

**Comment by simon04** [comment]
True. But [since the bot only looks for `wd:Q341`](https://github.com/konstin/github-wikidata-bot/blob/6cf29b7/free_software_items.rq#L5), items in the other categories won't get the automatic updates.

**Comment by konstin** [comment]
Thanks for contributing this query, but what is its purpose in the context of the bot? Are there plans to integrate that query with the bot?

**Comment by konstin** [comment]
@Nudin Unfortunately, the query you posted doesnt't work:

    Query is malformed: QName 'v:P31' uses an undefined prefix

**Comment by Nudin** [comment]
@konstin Sry – stupid non-stand prefix from the time where there was no standard… This is how it should be today:
```
  {
   ?floss p:P31 ?val.
   ?val ps:P31/wdt:P279* wd:Q506883.
  } Union {
   ?floss p:P31 ?val.
   ?val ps:P31/wdt:P279* wd:Q341.
  } Union {
   ?floss p:P31 ?val.
   ?val ps:P31/wdt:P279* wd:Q1130645.
  }
```

**Comment by Nudin** [comment]
Just an Idea:

I just quickly tried the following with query.csv being the first results of the query.
```
for name in $(cat query.csv | cut -d, -f2); do
  curl -sSfI https://github.com/${name}/${name} > /dev/null 2>&1 && echo $name
done
```
Results in 15% hits – we would need to check the hits by hand probably – maybe we can get this into wikidata games? Would have the potential to increase the outreach of the bot.

**Comment by konstin** [comment]
Using the updated query, there are 50 more result (641 vs. 591). Some of them are duplicates with different github urls (https://github.com/dae/anki vs. https://github.com/dae/anki.git), which should be removed before deploying the new query.

```sparql
PREFIX schema: <http://schema.org/>

SELECT DISTINCT ?project ?projectLabel ?article ?repo WHERE {
  # Free Software projects
  {
   ?project p:P31 ?val.
   ?val ps:P31/wdt:P279* wd:Q506883.
  } Union {
   ?project p:P31 ?val.
   ?val ps:P31/wdt:P279* wd:Q341.
  } Union {
   ?project p:P31 ?val.
   ?val ps:P31/wdt:P279* wd:Q1130645.
  }

  ?project wdt:P1324 ?repo.

  # Exclude projects not hosted on github
  FILTER(STRSTARTS(STR(?repo), "https://github.com")).

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }

  # Get the corresponding wikipedia page
  ?article schema:about ?project .
  ?article schema:inLanguage "en" .
  ?article schema:isPartOf <https://en.wikipedia.org/>
}
ORDER BY ?projectLabel
```

**Comment by simon04** [comment]
Ad https://github.com/konstin/github-wikidata-bot/pull/1#issuecomment-299709754 and the purpose: I thought of adding a section to the README guiding the Wikidatans (does this word already exist?) what to do in order to get more software projects automatically updated with this bot:
* Does the entity already have a VCS repository set? Use this query do determine entities w/o repository.
* Does the project use GitHub releases? If not, no automatic update is possible at the moment.
* ...

**Comment by konstin** [comment]
This seems reasonable to me. If you add a section in the readme telling folks to use this query in order to find missing data, I'll merge :)

**Comment by simon04** [comment]
Sorry for my long response time. I added a section to README (19accf5).

**Comment by konstin** [comment]
Thanks!

**Pull request merged**
