### PR TITLE
Improve format of sources

### PR DESCRIPTION
**Pull request by Nudin**
- [x] Use url to human readable page not to api endpoint  #3
- [x] Add publishing date
- [x] Add title

### CODE REVIEW

**Comment by Nudin** [comment]
So from the technical point of view this is done and could be merged. There's however one open question:
The bot now adds the sources with the 'new' URLs also when previously there was already a source added by previous version of the bot. See [version 0.9.5.2 of Q21996240](https://www.wikidata.org/wiki/Q21996240) for the result of a test edit.

We could let it that way, since there is no bigger problem with having two sources. Or we could remove the old more vague sources. But even if we decide to remove them, I would not build it into github-wiki-bot but use a separate script – building it into github-wiki-bot would be technically messy and we would basically only need it in the first run after the update.

So from my point, we could merge this and let the bot running and adding the improved sources and then discuss on Wikidata whether to remove the redundant sources or not.

**Comment by konstin** [comment]
Imho the old sources aren't to much of a problem, so I agree that they could be remove by a one-off script. Everything else look good and also fixes #3!

**Comment by konstin** [comment]
There's one thing I just found when testing: In cases where the github release name (as opposed to the tag name) is not just the version or the tag, that name would be preferable as reference title.

**Comment by Nudin** [comment]
Yes, I also thought about that but didn't find a solution that was satisfying in all cases, since the release name sometimes only contains the version number and sometime it contains more, sometimes up to a full sentence. I'll create another ticket for improving this further.

**Comment by konstin** [comment]
FYI I've removed the github api as source

**Pull request merged**
